### ISSUE TITLE
Where to specify GPUs to use?

### ISSUE THREAD

**Issue by xingyi-li** [chenhsuanlin/signed-distance-SRN#1]
Hi! I really appreciate your work. However, I encounter an error "RuntimeError: CUDA out of memory. Tried to allocate 80.00 MiB (GPU 0; 10.92 GiB total capacity; 833.88 MiB already allocated; 58.00 MiB free; 938.00 MiB reserved in total by PyTorch)", and I check out that the GPU0 has been used by others. I want to use another GPU but I find that it is not trivial to find where to specify GPUs. So may I know where to specify GPUs?

**Comment by chenhsuanlin** [comment]
Just add `--gpu=1` for GPU #1! 🙂 Sorry for the confusion, I'm still working on completing the documentation.

**Comment by xingyi-li** [comment]
@chenhsuanlin Thank you!!!
