### ISSUE TITLE
how to test

### ISSUE THREAD

**Issue by peppa114** [chenhsuanlin/signed-distance-SRN#12]
I want to use a picture to test this network to directly generate output (such as  .ply files). Do you have a test script?

**Comment by chenhsuanlin** [comment]
I don't have a script to directly do so right now, but it should be fairly easy to modify from the [eval function](https://github.com/chenhsuanlin/signed-distance-SRN/blob/main/model/sdf_srn.py#L23).
The parts of code you'll want to pay attention to are [this function](https://github.com/chenhsuanlin/signed-distance-SRN/blob/main/model/sdf_srn.py#L30) that runs the SDF-SRN network, [this function](https://github.com/chenhsuanlin/signed-distance-SRN/blob/main/eval_3D.py#L41) that generates the mesh using marching cubes, and [this function](https://github.com/chenhsuanlin/signed-distance-SRN/blob/main/model/sdf_srn.py#L124) that saves the mesh.

**Comment by peppa114** [comment]
Thank you for your help
