### ISSUE TITLE
how to test with my photos

### ISSUE THREAD

**Issue by Kammagod** [chenhsuanlin/signed-distance-SRN#13]
hi,
I want to test my own picture, does the network input have to have the corresponding MASK.PNG?

**Comment by chenhsuanlin** [comment]
If you only wish to do inference with the network, you only need the RGB image as the input (see [these lines](https://github.com/chenhsuanlin/signed-distance-SRN/blob/main/model/sdf_srn.py#L172-L173)).
Also please refer to #12 on how to modify the code to test with your own image.
