### ISSUE TITLE
Input image resolution

### ISSUE THREAD

**Issue by akaganeite** [chenhsuanlin/signed-distance-SRN#14]
Thanks for sharing the code, it's a great work!
I was wondering whether a higher resolution of the input RGB image will improve the quality of output 3D model?

**Comment by chenhsuanlin** [comment]
Hi @akaganeite, training with higher-res images could help improve the output quality, but since SDF-SRN trains on static images which is a highly ill-posed problem, it's probably not something that could be fixed in totality solely by increasing image resolutions. Hope this helps!
