### ISSUE TITLE
Train with other datasets

### ISSUE THREAD

**Issue by akaganeite** [chenhsuanlin/signed-distance-SRN#15]
Would it be possible to train SDF-SRN on another dataset?
If it is possible, what should i prepare for the training process?
thanks.

**Comment by chenhsuanlin** [comment]
Hi @akaganeite, you would need a training dataset where each sample includes (1) the RGB image, (2) the object mask, and (3) the object's camera pose (with the category semantically aligned, e.g. with the same orientations). Hope this helps!
