### ISSUE TITLE
Using pre-trained Implicit network to render novel views?

### ISSUE THREAD

**Issue by rajat95** [chenhsuanlin/signed-distance-SRN#6]
Though I can render novel views using reconstructed mesh, but I was wondering if it's possible to render new views or zoom into the 3D model; using the implicit network alone? I tried changing the camera distance for zoom but that doesn't lead to any change in  reconstructed RGB view.

**Comment by chenhsuanlin** [comment]
Sorry for the late reply -- are you trying to render novel views from a pretrained model? It would be great if you could provide some examples of what you're trying to do. Also, if you're working on Pascal3D+, this would be pretty much expected because we assume orthographic projections here.

**Comment by chenhsuanlin** [comment]
Closing this issue due to no response. Please feel free to reopen if there are follow-up questions!
