### ISSUE TITLE
Rendering script for Pascal3D+

### ISSUE THREAD

**Issue by OliverZYQ** [chenhsuanlin/signed-distance-SRN#9]
Thanks for sharing the code, it's a great work!
Can you provide the script for Pascal 3D+ datasets to generate masks and ground-truth point clouds for other categories? Thank you very much!

**Comment by chenhsuanlin** [comment]
The ground-truth segmentation masks were generated using the provided [toolbox](https://cvgl.stanford.edu/projects/pascal3d.html), which was written in Matlab.
I can get to releasing the script for creating ground-truth point clouds, but it will probably have to wait a couple of weeks. Leaving this issue open for now.

**Comment by chenhsuanlin** [comment]
I've just updated the [readme](https://github.com/chenhsuanlin/signed-distance-SRN/blob/main/data/README.md) and included the instructions for creating ground-truth point clouds for PASCAL3D+. Please let me know if you have further questions, and feel free to reopen the issue if necessary 🙂

**Comment by OliverZYQ** [comment]
Thanks!
